### ISSUE TITLE
Is the dataset available online?

### ISSUE THREAD

**Issue by BarclayII** [DGraphXinye/DGraphFin_baseline#1]
Thanks for making this dataset available!

I have looked into the homepage in dgraph.xinye.com but I could not find the link of the dataset, and the code here do not seem to have a URL.  Is the dataset available anywhere?

**Comment by DGraphXinye** [comment]
![20220707183606](https://user-images.githubusercontent.com/104020755/177754425-ce73e4fa-8334-4e14-b001-6ceaf43345d7.png)
Hello BarclayII, have you signed up at dgraph.xinye.com? Once you logged in, you would be able to see a download sign in the statistics form.
